// CHEF FACTORY — Gate 46 — Verification Session.
//
// A trusted in-memory identity for one Gate46 acceptance execution, binding the
// pre/post workspace fingerprint to the verification operations and the final
// accepted decision. The session ID is generated by trusted infrastructure only.
//
//   MODEL_CAN_SUPPLY_SESSION_ID = NO
//   AGENT_CAN_SUPPLY_SESSION_ID = NO
//
// The session itself is ephemeral (in-memory). A MINIMAL projection (session_id +
// workspace_fingerprint) is persisted to task_verifications as AUDIT-ONLY evidence;
// historical evidence NEVER authorizes future completion.

import { randomUUID } from 'node:crypto';
import type { VerificationOperation, VerificationResult } from './types.js';

export type WorkspaceFingerprint = string | null;

export interface VerificationSession {
  sessionId: string;
  ownerId: string;
  projectId: string | null;
  taskId: string;
  taskAttempt: number;
  /** Trusted workspace fingerprint captured BEFORE running verification ops. */
  fingerprintBefore: WorkspaceFingerprint;
  requiredOperations: readonly VerificationOperation[];
  verificationResults: VerificationResult[];
  /** Trusted workspace fingerprint captured AFTER running verification ops. */
  fingerprintAfter: WorkspaceFingerprint;
  /** True only when the session fence (before==after) held AND all checks passed. */
  accepted: boolean;
  /** Deterministic session classification (passed | repairable | nonRepairable | blocked). */
  classification: 'passed' | 'repairable' | 'nonRepairable' | 'blocked';
}

/** Generate a trusted session ID. MODEL/AGENT_CAN_SUPPLY_SESSION_ID = NO. */
export function newSessionId(): string {
  return randomUUID();
}
